### PR TITLE
Merge golang/protobuf/master to improbable_current branch

### PR DESCRIPTION
**Pull request by stefan-improbable**
This is required to update/get rid of forks in platform.git repo.

Testing strategy: I'll try to run SHA of current commit on improbable_current_update on buildkite.

### CODE REVIEW

**Comment by DoomGerbil** [comment]
I think that this is something we're going to need to announce widely before we do it just so people know to watch for issues.

Hopefully we can start updating this more regularly so we don't have these huge big-bang updates like this, and those we hopefully wouldn't need to announce.

**Review by DoomGerbil — APPROVED** [review]

**Review by Helcaraxan — CHANGES_REQUESTED** [review]
Thank you very much for making this effort. 👏 

However a few points that we **need** to clear up before we can merge this:
- We need to clarify how this change will interact with our current protobuf/protobuf version / fork.
- We need to ensure that this does not have any knock-on effect on the Fabric repo (it shouldn't but still...).
- We should get reviews or at least comments from a few more people familiar with our Protobuf setup.

Do help addressing these points it would be good if we could have a shortlist of relevant changes (to our use-case) that this PR merges from the upstream.

Putting my review in as "Request Changes" as a ⚠️ sign to ensure we don't accidentally merge this until all the above has been cleared up.

**Comment by stefan-improbable** [comment]
@devnev @kdima FYI I'm trying to upgrade golang/protobuf in platform.git.

**Comment by stefan-improbable** [comment]
The changes in to our fork (I have found out so far are):
- golang protobuf structs are no longer comparable via assert.Equal and ==
- golang protobufs can not be used as map keys
- serializing protobuf string field fails if it's not UTF-8, we have to use bytes instead

**Comment by stefan-improbable** [comment]
> Thank you very much for making this effort. 
> 
> However a few points that we **need** to clear up before we can merge this:
> 
> * We need to clarify how this change will interact with our current protobuf/protobuf version / fork.
> * We need to ensure that this does not have any knock-on effect on the Fabric repo (it shouldn't but still...).
> * We should get reviews or at least comments from a few more people familiar with our Protobuf setup.
> 
> Do help addressing these points it would be good if we could have a shortlist of relevant changes (to our use-case) that this PR merges from the upstream.
> 
> Putting my review in as "Request Changes" as a  sign to ensure we don't accidentally merge this until all the above has been cleared up.

@Helcaraxan given that I've done some tests as described in https://docs.google.com/document/d/1mGCE8qEp4B1KTbyOl8G2k4W65g8wePoj0xBziFTe46M/edit# , can we consider this comment addressed?

**Review by Helcaraxan — APPROVED** [review]

**Pull request merged**
